"""SOUL.md 永続化 (hersona.core.soul) の回帰テスト (ROADMAP §⑤)。

- `render_soul`: blend → SOUL.md 形式 markdown
- `write_soul`: ファイル書き出し (新規 / 上書き / append / 既存で FileExistsError)
- `default_soul_path`: パス解決
- i18n: ja / en
- 異常系: 空 blend / 不正 weight / 親ディレクトリなし
"""
from __future__ import annotations

import tempfile
from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import patch

import pytest

from hersona.core.soul import default_soul_path, render_soul, write_soul

_FIXED_DT = datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc)

# --- render_soul ----------------------------------------------------------


def test_render_soul_minimal_tsundere() -> None:
    content = render_soul(["personality/tsundere"], weight="moderate")
    # 公式 4 要素のヘッダーが含まれる
    assert "## 1. Name (エージェント名)" in content
    assert "## 2. Personality (性格特性)" in content
    assert "## 3. Tone (口調)" in content
    assert "## 4. Behavioral Guidelines (行動指針)" in content
    # メタコメントが先頭にある
    assert content.startswith("<!-- generated by hersona v")
    assert "DO NOT EDIT" in content
    # tsundere の core_traits が ja で埋まる
    assert "素直になれない" in content
    assert "照れ隠し" in content


def test_render_soul_with_speech_attribute() -> None:
    content = render_soul(
        ["personality/tsundere", "speech/keigo"], weight="moderate"
    )
    # Personality セクション
    assert "### 2.1 personality/tsundere" in content
    # Tone セクション: keigo が独立
    assert "### 3.1 speech/keigo" in content
    # keigo の catchphrases が出現
    assert "catchphrases" in content.lower()


def test_render_soul_weight_variants() -> None:
    for level in ("none", "mild", "moderate", "strong"):
        content = render_soul(["personality/tsundere"], weight=level)
        assert f"### 4.1 鉄則 (強度: {level})" in content


def test_render_soul_empty_raises() -> None:
    with pytest.raises(ValueError, match="blend が空"):
        render_soul([])


def test_render_soul_unknown_attribute_raises() -> None:
    with pytest.raises(KeyError):
        render_soul(["personality/nonexistent_attribute_xyz"])


def test_render_soul_conflict_raises() -> None:
    """tsundere と protective の conflict 検出で ValueError。

    (tsundere の `conflicts` frozenset に `protective` が含まれる。
    playful は skill doc 上の NG 例だが、matrix には未登録。)
    """
    with pytest.raises(ValueError, match="conflict"):
        render_soul(["personality/tsundere", "personality/protective"])


def test_render_soul_normalizes_category_prefix() -> None:
    """`<category>/<name>` 形式と `<name>` 形式が同じ人格レンダリングになる。

    datetime.now をモックして両呼び出しのタイムスタンプを固定することで
    決定論的な比較を保証する (CI フレーキー防止)。
    `<!-- blend:` 行は入力形式を保持するため除外して本文のみ比較する。
    """
    with patch("hersona.core.soul.datetime") as mock_dt:
        mock_dt.now.return_value = _FIXED_DT
        a = render_soul(["personality/tsundere"], weight="moderate")
        b = render_soul(["tsundere"], weight="moderate")

    def _strip_blend_meta(lines: list[str]) -> list[str]:
        return [ln for ln in lines if not ln.startswith("<!-- blend:")]

    assert _strip_blend_meta(a.splitlines()) == _strip_blend_meta(b.splitlines())
    # メタコメント自体は元の入力を保持
    assert "<!-- blend: personality/tsundere -->" in a
    assert "<!-- blend: tsundere -->" in b


# --- write_soul -----------------------------------------------------------


def test_write_soul_creates_file(tmp_path: Path) -> None:
    out = tmp_path / "SOUL.md"
    result = write_soul(out, ["personality/tsundere"], weight="moderate", overwrite=True)
    assert result.output_path == out
    assert out.exists()
    assert out.read_text(encoding="utf-8").startswith("<!-- generated by hersona")
    # SOULRenderResult のフィールド
    assert result.blend_names == ["personality/tsundere"]
    assert result.weight.value == "moderate"
    assert result.lang == "ja"


def test_write_soul_existing_file_raises_without_overwrite(tmp_path: Path) -> None:
    out = tmp_path / "SOUL.md"
    out.write_text("# existing", encoding="utf-8")
    with pytest.raises(FileExistsError):
        write_soul(out, ["personality/tsundere"], weight="moderate")


def test_write_soul_overwrite_true_replaces(tmp_path: Path) -> None:
    out = tmp_path / "SOUL.md"
    out.write_text("# existing", encoding="utf-8")
    result = write_soul(
        out, ["personality/tsundere"], weight="moderate", overwrite=True
    )
    assert "existing" not in out.read_text(encoding="utf-8")
    assert result.content.startswith("<!-- generated by hersona")


def test_write_soul_force_replaces(tmp_path: Path) -> None:
    out = tmp_path / "SOUL.md"
    out.write_text("# existing", encoding="utf-8")
    result = write_soul(
        out, ["personality/tsundere"], weight="moderate", force=True
    )
    assert "existing" not in out.read_text(encoding="utf-8")
    assert result.content.startswith("<!-- generated by hersona")


def test_write_soul_append_adds_section(tmp_path: Path) -> None:
    out = tmp_path / "SOUL.md"
    out.write_text("# existing content\n\n", encoding="utf-8")
    write_soul(
        out, ["personality/tsundere"], weight="mild", append=True
    )
    text = out.read_text(encoding="utf-8")
    assert "existing content" in text
    assert "## 追記" in text
    assert "weight=mild" in text


def test_write_soul_missing_parent_raises(tmp_path: Path) -> None:
    out = tmp_path / "nonexistent-dir" / "SOUL.md"
    with pytest.raises(FileNotFoundError, match="親ディレクトリ"):
        write_soul(out, ["personality/tsundere"], weight="moderate", overwrite=True)


# --- default_soul_path ----------------------------------------------------


def test_default_soul_path_is_hermes_home() -> None:
    # Local Hermes CLI は get_hermes_home() / "SOUL.md" を読む。
    # profile 別パス (profiles/<name>/SOUL.md) は Hermes One 専用で Local CLI 未対応。
    p = default_soul_path()
    assert p == Path.home() / ".hermes" / "SOUL.md"


def test_default_soul_path_ignores_profile_arg() -> None:
    # profile 引数は後方互換のため残すが、現在は無視される。
    assert default_soul_path("tsundere-poster") == default_soul_path()


# --- パブリック API --------------------------------------------------------


def test_soul_api_exported_from_core() -> None:
    """`hersona.core` から公開されている (PUBLIC_API.md と整合)。"""
    from hersona.core import (  # noqa: F401
        SoulRenderResult,
    )


# --- E2E: write_soul で書いた SOUL.md が公式 4 要素を満たす --------------


def test_written_soul_md_has_official_four_sections(tmp_path: Path) -> None:
    """Hermes One 公式仕様 (hermesagents.cc) の 4 要素を含む。"""
    out = tmp_path / "SOUL.md"
    write_soul(
        out,
        ["personality/tsundere", "speech/keigo"],
        weight="moderate",
        overwrite=True,
    )
    text = out.read_text(encoding="utf-8")
    for header in (
        "## 1. Name (エージェント名)",
        "## 2. Personality (性格特性)",
        "## 3. Tone (口調)",
        "## 4. Behavioral Guidelines (行動指針)",
    ):
        assert header in text, f"missing official section: {header}"


# --- cleanup --------------------------------------------------------------


@pytest.fixture
def cleanup_temp_soul_files():
    """テスト後に /tmp/hermes-test などを掃除する fixture (保険)。"""
    yield
    leftover = Path(tempfile.gettempdir()) / "hermes-test"
    if leftover.exists():
        import shutil
        shutil.rmtree(leftover, ignore_errors=True)
