"""SOUL.md 永続化 (hersona.core.soul) の回帰テスト (ROADMAP §⑤)。

- `render_soul`: blend → SOUL.md 形式 markdown
- `write_soul`: ファイル書き出し (新規 / 上書き / append / 既存で FileExistsError)
- `default_soul_path`: パス解決
- i18n: ja / en
- 異常系: 空 blend / 不正 weight / 親ディレクトリなし
"""
from __future__ import annotations

import tempfile
from pathlib import Path

import pytest

from hersona.core.soul import default_soul_path, render_soul, write_soul

# --- render_soul ----------------------------------------------------------


def test_render_soul_minimal_tsundere() -> None:
    content = render_soul(["personality/tsundere"], weight="moderate")
    # 公式 4 要素のヘッダーが含まれる
    assert "## 1. Name (エージェント名)" in content
    assert "## 2. Personality (性格特性)" in content
    assert "## 3. Tone (口調)" in content
    assert "## 4. Behavioral Guidelines (行動指針)" in content
    # メタコメントが先頭にある
    assert content.startswith("<!-- generated by hersona v")
    assert "DO NOT EDIT" in content
    # tsundere の core_traits が ja で埋まる
    assert "素直になれない" in content
    assert "照れ隠し" in content


def test_render_soul_with_speech_attribute() -> None:
    content = render_soul(
        ["personality/tsundere", "speech/keigo"], weight="moderate"
    )
    # Personality セクション
    assert "### 2.1 personality/tsundere" in content
    # Tone セクション: keigo が独立
    assert "### 3.1 speech/keigo" in content
    # keigo の catchphrases が出現
    assert "catchphrases" in content.lower()


def test_render_soul_weight_variants() -> None:
    for level in ("none", "mild", "moderate", "strong"):
        content = render_soul(["personality/tsundere"], weight=level)
        assert f"### 4.1 鉄則 (強度: {level})" in content


def test_render_soul_empty_raises() -> None:
    with pytest.raises(ValueError, match="blend が空"):
        render_soul([])


def test_render_soul_unknown_attribute_raises() -> None:
    with pytest.raises(KeyError):
        render_soul(["personality/nonexistent_attribute_xyz"])


def test_render_soul_conflict_raises() -> None:
    """tsundere と protective の conflict 検出で ValueError。

    (tsundere の `conflicts` frozenset に `protective` が含まれる。
    playful は skill doc 上の NG 例だが、matrix には未登録。)
    """
    with pytest.raises(ValueError, match="conflict"):
        render_soul(["personality/tsundere", "personality/protective"])


def test_render_soul_normalizes_category_prefix() -> None:
    """`<category>/<name>` 形式と `<name>` 形式が同じ人格レンダリングになる。

    メタコメント (`<!-- generated -->` / `<!-- blend: -->`) と
    フッターのタイムスタンプ行は実行時刻で揺れるので除外して比較する。
    """
    a = render_soul(["personality/tsundere"], weight="moderate")
    b = render_soul(["tsundere"], weight="moderate")

    def _strip_volatile(lines: list[str]) -> list[str]:
        out: list[str] = []
        for line in lines:
            if line.startswith("<!-- generated"):
                continue
            if line.startswith("<!-- blend:"):
                continue
            if line.startswith("_作成:"):
                continue
            out.append(line)
        return out

    a_stripped = _strip_volatile(a.splitlines())
    b_stripped = _strip_volatile(b.splitlines())
    assert a_stripped == b_stripped
    # メタコメント自体は元の入力を保持
    assert "<!-- blend: personality/tsundere -->" in a
    assert "<!-- blend: tsundere -->" in b


# --- write_soul -----------------------------------------------------------


def test_write_soul_creates_file(tmp_path: Path) -> None:
    out = tmp_path / "SOUL.md"
    result = write_soul(out, ["personality/tsundere"], weight="moderate", overwrite=True)
    assert result.output_path == out
    assert out.exists()
    assert out.read_text(encoding="utf-8").startswith("<!-- generated by hersona")
    # SOULRenderResult のフィールド
    assert result.blend_names == ["personality/tsundere"]
    assert result.weight.value == "moderate"
    assert result.lang == "ja"


def test_write_soul_existing_file_raises_without_overwrite(tmp_path: Path) -> None:
    out = tmp_path / "SOUL.md"
    out.write_text("# existing", encoding="utf-8")
    with pytest.raises(FileExistsError):
        write_soul(out, ["personality/tsundere"], weight="moderate")


def test_write_soul_overwrite_true_replaces(tmp_path: Path) -> None:
    out = tmp_path / "SOUL.md"
    out.write_text("# existing", encoding="utf-8")
    result = write_soul(
        out, ["personality/tsundere"], weight="moderate", overwrite=True
    )
    assert "existing" not in out.read_text(encoding="utf-8")
    assert result.content.startswith("<!-- generated by hersona")


def test_write_soul_force_replaces(tmp_path: Path) -> None:
    out = tmp_path / "SOUL.md"
    out.write_text("# existing", encoding="utf-8")
    result = write_soul(
        out, ["personality/tsundere"], weight="moderate", force=True
    )
    assert "existing" not in out.read_text(encoding="utf-8")
    assert result.content.startswith("<!-- generated by hersona")


def test_write_soul_append_adds_section(tmp_path: Path) -> None:
    out = tmp_path / "SOUL.md"
    out.write_text("# existing content\n\n", encoding="utf-8")
    write_soul(
        out, ["personality/tsundere"], weight="mild", append=True
    )
    text = out.read_text(encoding="utf-8")
    assert "existing content" in text
    assert "## 追記" in text
    assert "weight=mild" in text


def test_write_soul_missing_parent_raises(tmp_path: Path) -> None:
    out = tmp_path / "nonexistent-dir" / "SOUL.md"
    with pytest.raises(FileNotFoundError, match="親ディレクトリ"):
        write_soul(out, ["personality/tsundere"], weight="moderate", overwrite=True)


# --- default_soul_path ----------------------------------------------------


def test_default_soul_path_is_hermes_home() -> None:
    # Local Hermes CLI は get_hermes_home() / "SOUL.md" を読む。
    # profile 別パス (profiles/<name>/SOUL.md) は Hermes One 専用で Local CLI 未対応。
    p = default_soul_path()
    assert p == Path.home() / ".hermes" / "SOUL.md"


def test_default_soul_path_ignores_profile_arg() -> None:
    # profile 引数は後方互換のため残すが、現在は無視される。
    assert default_soul_path("tsundere-poster") == default_soul_path()


# --- パブリック API --------------------------------------------------------


def test_soul_api_exported_from_core() -> None:
    """`hersona.core` から公開されている (PUBLIC_API.md と整合)。"""
    from hersona.core import (  # noqa: F401
        SoulRenderResult,
    )


# --- E2E: write_soul で書いた SOUL.md が公式 4 要素を満たす --------------


def test_written_soul_md_has_official_four_sections(tmp_path: Path) -> None:
    """Hermes One 公式仕様 (hermesagents.cc) の 4 要素を含む。"""
    out = tmp_path / "SOUL.md"
    write_soul(
        out,
        ["personality/tsundere", "speech/keigo"],
        weight="moderate",
        overwrite=True,
    )
    text = out.read_text(encoding="utf-8")
    for header in (
        "## 1. Name (エージェント名)",
        "## 2. Personality (性格特性)",
        "## 3. Tone (口調)",
        "## 4. Behavioral Guidelines (行動指針)",
    ):
        assert header in text, f"missing official section: {header}"


# --- memory (Recent Context) ----------------------------------------------


def test_render_soul_with_memory_emits_recent_context() -> None:
    content = render_soul(
        ["personality/tsundere"],
        weight="moderate",
        memory={"last_topic": "ReAct パターン"},
    )
    assert "## Recent Context" in content
    assert "### last_topic: ReAct パターン" in content


def test_render_soul_memory_empty_dict_omits_block() -> None:
    content = render_soul(["personality/tsundere"], weight="moderate", memory={})
    assert "## Recent Context" not in content


def test_render_soul_memory_none_omits_block() -> None:
    content = render_soul(["personality/tsundere"], weight="moderate", memory=None)
    assert "## Recent Context" not in content


def test_render_soul_memory_rejects_too_many_keys() -> None:
    memory = {f"key_{i}": "v" for i in range(17)}
    with pytest.raises(ValueError, match="17 keys"):
        render_soul(["personality/tsundere"], memory=memory)


def test_render_soul_memory_rejects_oversized_value() -> None:
    with pytest.raises(ValueError, match="513"):
        render_soul(
            ["personality/tsundere"],
            memory={"topic": "x" * 513},
        )


def test_render_soul_memory_escapes_markdown_specials() -> None:
    content = render_soul(
        ["personality/tsundere"],
        memory={"topic": "## header\n[link](evil) `code` *bold* _italic_"},
    )
    section = content.split("## Recent Context", 1)[1]
    assert "## header" not in section
    assert "[link]" not in section
    assert "`code`" not in section
    assert "*bold*" not in section
    assert "_italic_" not in section
    assert "\\#\\# header" in section
    assert "\\[link\\]" in section


def test_render_soul_memory_is_deterministic() -> None:
    mem = {"topic": "ReAct パターン", "mood": "やや真剣"}

    def _strip_volatile(text: str) -> list[str]:
        out: list[str] = []
        for line in text.splitlines():
            if line.startswith("<!-- generated"):
                continue
            if line.startswith("_作成:"):
                continue
            out.append(line)
        return out

    r1 = render_soul(["personality/tsundere"], memory=mem)
    r2 = render_soul(["personality/tsundere"], memory=mem)
    assert _strip_volatile(r1) == _strip_volatile(r2)
    assert "## Recent Context" in r1
    assert "### topic: ReAct パターン" in r1


def test_write_soul_with_memory_persists_to_disk(tmp_path: Path) -> None:
    out = tmp_path / "SOUL.md"
    memory = {"mood": "真剣"}
    result = write_soul(
        out,
        ["personality/tsundere"],
        weight="moderate",
        overwrite=True,
        memory=memory,
    )
    text = out.read_text(encoding="utf-8")
    assert "## Recent Context" in text
    assert "### mood: 真剣" in text
    assert result.memory == memory


# --- cleanup --------------------------------------------------------------


@pytest.fixture
def cleanup_temp_soul_files():
    """テスト後に /tmp/hermes-test などを掃除する fixture (保険)。"""
    yield
    leftover = Path(tempfile.gettempdir()) / "hermes-test"
    if leftover.exists():
        import shutil
        shutil.rmtree(leftover, ignore_errors=True)
