"""persistent モード (hersona.core.persistent) の回帰テスト (ROADMAP §⑤.1)。

- `run_persistent`: SOUL.md 自動書き出し + config.yaml ブロック生成
- フラグ: --without-soul / --without-config / --force / --config-yaml-output
- persona 名の自動生成規則
"""
from __future__ import annotations

import tempfile
from pathlib import Path

import pytest

from hersona.core.persistent import (
    _generate_persona_name,
    apply_personality,
    run_persistent,
)
from hersona.core.weight import WeightLevel


@pytest.fixture
def fake_hermes_profile(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    """default_soul_path が指す先を tmp_path に差し替える。"""
    target = tmp_path / "profiles" / "default"
    target.mkdir(parents=True)

    def _fake_soul_path(profile: str = "default") -> Path:
        return target / "SOUL.md"

    monkeypatch.setattr(
        "hersona.core.persistent.default_soul_path", _fake_soul_path
    )
    # `hersona.core.soul.default_soul_path` もパッチ (write_soul が直接参照するため)
    monkeypatch.setattr(
        "hersona.core.soul.default_soul_path", _fake_soul_path
    )
    return target


# --- _generate_persona_name ----------------------------------------------


def test_generate_persona_name_basic() -> None:
    name = _generate_persona_name(
        ["personality/tsundere", "speech/keigo"], weight=WeightLevel.MODERATE
    )
    assert name == "tsundere_keigo_moderate"


def test_generate_persona_name_strips_category() -> None:
    """`<category>/` プレフィックスは persona 名に含めない。"""
    a = _generate_persona_name(
        ["personality/tsundere"], weight=WeightLevel.MODERATE
    )
    b = _generate_persona_name(["tsundere"], weight=WeightLevel.MODERATE)
    assert a == b == "tsundere_moderate"


def test_generate_persona_name_all_weights() -> None:
    for w in (
        WeightLevel.NONE,
        WeightLevel.MILD,
        WeightLevel.MODERATE,
        WeightLevel.STRONG,
    ):
        name = _generate_persona_name(["tsundere"], weight=w)
        assert name.endswith(f"_{w.value}")


def test_generate_persona_name_strips_invalid_chars() -> None:
    name = _generate_persona_name(["tsundere"], weight=WeightLevel.MODERATE)
    assert all(c.isalnum() or c == "_" for c in name)


def test_generate_persona_name_includes_use_case() -> None:
    name = _generate_persona_name(
        ["personality/tsundere", "speech/keigo"],
        weight=WeightLevel.MODERATE,
        use_case="planner",
    )
    assert name == "tsundere_keigo_planner_moderate"


# --- run_persistent (デフォルト動作) -------------------------------------


def test_run_persistent_default_writes_soul_and_returns_block(
    fake_hermes_profile: Path,
) -> None:
    result = run_persistent(
        ["personality/tsundere", "speech/keigo"],
        weight="moderate",
    )
    # persona 名 (v1.8.0: persona_lock が既定で blend に付加される)
    assert result.persona_name == "tsundere_keigo_persona_lock_moderate"
    # config.yaml ブロック
    assert "personalities:" in result.config_yaml_block
    assert f"  {result.persona_name}: |" in result.config_yaml_block
    # SOUL.md は既定で ON
    assert result.soul_result is not None
    assert fake_hermes_profile.joinpath("SOUL.md").exists()
    assert "tsundere" in fake_hermes_profile.joinpath("SOUL.md").read_text(
        encoding="utf-8"
    )


def test_run_persistent_existing_soul_raises_without_force(
    fake_hermes_profile: Path,
) -> None:
    fake_hermes_profile.joinpath("SOUL.md").write_text(
        "# existing", encoding="utf-8"
    )
    with pytest.raises(FileExistsError):
        run_persistent(["personality/tsundere"], weight="moderate")


def test_run_persistent_force_overwrites(fake_hermes_profile: Path) -> None:
    soul_path = fake_hermes_profile / "SOUL.md"
    soul_path.write_text("# existing", encoding="utf-8")
    result = run_persistent(
        ["personality/tsundere"], weight="moderate", force=True
    )
    assert result.soul_result is not None
    assert "existing" not in soul_path.read_text(encoding="utf-8")
    assert "<!-- generated by hersona" in soul_path.read_text(encoding="utf-8")


def test_run_persistent_with_use_case_writes_soul_and_config(
    fake_hermes_profile: Path,
) -> None:
    result = run_persistent(
        ["personality/tsundere", "speech/keigo"],
        weight="moderate",
        use_case="planner",
    )
    assert result.persona_name == "tsundere_keigo_persona_lock_planner_moderate"
    assert result.use_case == "planner"
    assert "## Operating Mode: Strategic Planner" in result.config_yaml_block
    assert result.soul_result is not None
    assert result.soul_result.use_case == "planner"
    assert "## Operating Mode: Strategic Planner" in fake_hermes_profile.joinpath("SOUL.md").read_text(
        encoding="utf-8"
    )


# --- フラグ --------------------------------------------------------------


def test_run_persistent_without_soul_skips_soul_write(
    fake_hermes_profile: Path,
) -> None:
    result = run_persistent(
        ["personality/tsundere"],
        weight="moderate",
        without_soul=True,
    )
    assert result.soul_result is None
    assert "soul" in result.skipped
    # SOUL.md は書き出されない
    assert not fake_hermes_profile.joinpath("SOUL.md").exists()
    # config.yaml ブロックは生成される
    assert "personalities:" in result.config_yaml_block


def test_run_persistent_without_config_skips_block(
    fake_hermes_profile: Path,
) -> None:
    result = run_persistent(
        ["personality/tsundere"],
        weight="moderate",
        without_config=True,
    )
    assert result.config_yaml_block == ""
    assert "config" in result.skipped
    # SOUL.md は書き出される
    assert fake_hermes_profile.joinpath("SOUL.md").exists()


def test_run_persistent_both_skipped(
    fake_hermes_profile: Path,
) -> None:
    result = run_persistent(
        ["personality/tsundere"],
        weight="moderate",
        without_soul=True,
        without_config=True,
    )
    assert result.soul_result is None
    assert result.config_yaml_block == ""
    # SOUL.md は書き出されない
    assert not fake_hermes_profile.joinpath("SOUL.md").exists()


def test_run_persistent_config_yaml_output_writes_file(
    fake_hermes_profile: Path, tmp_path: Path
) -> None:
    out_yaml = tmp_path / "persona.yaml"
    result = run_persistent(
        ["personality/tsundere"],
        weight="moderate",
        config_yaml_output=out_yaml,
    )
    assert out_yaml.exists()
    text = out_yaml.read_text(encoding="utf-8")
    assert "personalities:" in text
    # ブロックは config_block と同じ内容
    assert text.strip() == result.config_yaml_block.strip()


# --- 異常系 --------------------------------------------------------------


def test_run_persistent_empty_names_raises() -> None:
    with pytest.raises(ValueError, match="blend が空"):
        run_persistent([], weight="moderate")


def test_run_persistent_conflict_raises(fake_hermes_profile: Path) -> None:
    """tsundere + protective は conflict。"""
    with pytest.raises(ValueError, match="conflict"):
        run_persistent(
            ["personality/tsundere", "personality/protective"],
            weight="moderate",
        )


def test_run_persistent_unknown_attribute_raises(
    fake_hermes_profile: Path,
) -> None:
    with pytest.raises(KeyError):
        run_persistent(
            ["personality/nonexistent_attribute_xyz"],
            weight="moderate",
        )


# --- apply_personality ---------------------------------------------------


def test_apply_personality_hermes_not_found(monkeypatch: pytest.MonkeyPatch) -> None:
    """hermes コマンドが存在しない場合は 'hermes not found' を返す。"""
    import subprocess

    def _fake_run(cmd, **kwargs):
        raise FileNotFoundError("hermes not found")

    monkeypatch.setattr(subprocess, "run", _fake_run)
    result = apply_personality("tsundere_strong")
    assert result == "hermes not found"


def test_apply_personality_success(monkeypatch: pytest.MonkeyPatch) -> None:
    """hermes config set が成功する場合は 'ok' を返す。"""
    import subprocess

    captured: list[list[str]] = []

    class _FakeResult:
        returncode = 0
        stderr = ""
        stdout = ""

    def _fake_run(cmd, **kwargs):
        captured.append(cmd)
        return _FakeResult()

    monkeypatch.setattr(subprocess, "run", _fake_run)
    result = apply_personality("tsundere_strong")
    assert result == "ok"
    assert captured[0] == ["hermes", "config", "set", "agent.personality", "tsundere_strong"]


def test_run_persistent_apply_flag(
    fake_hermes_profile: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """apply=True のとき apply_result が設定される。"""
    import subprocess

    class _FakeResult:
        returncode = 0
        stderr = ""
        stdout = ""

    monkeypatch.setattr(subprocess, "run", lambda cmd, **kw: _FakeResult())
    result = run_persistent(["tsundere"], weight="mild", apply=True)
    assert result.apply_result == "ok"


def test_run_persistent_no_apply_by_default(fake_hermes_profile: Path) -> None:
    """apply=False (既定) では apply_result は None。"""
    result = run_persistent(["tsundere"], weight="mild")
    assert result.apply_result is None


# --- memory (Recent Context) ----------------------------------------------


def test_run_persistent_with_memory_propagates_to_soul(
    fake_hermes_profile: Path,
) -> None:
    memory = {"mood": "真剣"}
    result = run_persistent(
        ["personality/tsundere"],
        weight="moderate",
        force=True,
        memory=memory,
    )
    assert result.memory == memory
    assert result.soul_result is not None
    text = fake_hermes_profile.joinpath("SOUL.md").read_text(encoding="utf-8")
    assert "## Recent Context" in text
    assert "### mood: 真剣" in text


def test_run_persistent_memory_and_memory_file_are_mutually_exclusive(
    fake_hermes_profile: Path, tmp_path: Path
) -> None:
    memory_file = tmp_path / "memory.json"
    memory_file.write_text('{"mood": "真剣"}', encoding="utf-8")
    with pytest.raises(ValueError, match="mutually exclusive"):
        run_persistent(
            ["personality/tsundere"],
            weight="moderate",
            force=True,
            memory={"mood": "真剣"},
            memory_file=memory_file,
        )


# --- パブリック API -------------------------------------------------------


def test_persistent_api_exported_from_core() -> None:
    """`hersona.core` から公開されている。"""
    from hersona.core import (  # noqa: F401
        PersistentResult,
    )


# --- cleanup --------------------------------------------------------------


@pytest.fixture(autouse=True)
def cleanup_temp_hermes_test():
    yield
    leftover = Path(tempfile.gettempdir()) / "hermes-test"
    if leftover.exists():
        import shutil
        shutil.rmtree(leftover, ignore_errors=True)
