"""persistent モード (ROADMAP §⑤.1)。

blend を `~/.hermes/profiles/<name>/SOUL.md` に永続化し、次回セッションから
Hermes One 公式の人格ファイルとして自動適用させる。

設計判断 (SKILL.md §Pitfall と整合):
- `config.yaml` (`agent.personalities.<name>`) への書き込みは `auto_config=True`
  で有効化できる。`config_writer.write_personality` が PyYAML で直接ファイルを
  編集するため `hermes config set` (Pitfall 8: ネスト YAML 破壊) を回避する。
- `auto_config=False` (既定) では引き続き「追記用 YAML ブロック」を表示する。
- SOUL.md への自動書き出しは **既定で ON**。 `--without-soul` で OFF。
- 既存 SOUL.md の扱いは `write_soul` と整合: `--force` で強制上書き、
  未指定なら確認プロンプト相当の挙動 (write_soul が FileExistsError を送出)。
"""
from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from hersona.core.attach import load_attribute
from hersona.core.config_writer import ConfigWriteResult, write_personality
from hersona.core.soul import SoulRenderResult, default_soul_path, write_soul
from hersona.core.weight import WeightLevel, coerce_level

# persistent で生成する persona 名の snake_case 規則
_NAME_INVALID = re.compile(r"[^a-z0-9_]")
_NAME_SAFE_SEP = "_"


@dataclass
class PersistentResult:
    """persistent モード実行結果。"""

    persona_name: str  # config.yaml に追記する persona 名 (例: tsundere_keigo_moderate)
    config_yaml_block: str  # 表示 / ファイル書き出し用の YAML ブロック
    soul_result: SoulRenderResult | None  # SOUL.md 書き出し結果 (skip 時は None)
    config_write_result: ConfigWriteResult | None  # config.yaml 自動書き込み結果
    apply_result: str | None  # `hermes config set agent.personality <name>` の結果
    skipped: dict[str, str]  # skip された項目 (例: {"soul": "user request"})


def _generate_persona_name(names: list[str], weight: WeightLevel) -> str:
    """persona 名を `attr1_attr2_..._<weight>` 形式で自動生成する。"""
    parts: list[str] = []
    for n in names:
        # `<category>/<name>` 形式は name 部分だけ採用
        base = n.split("/", 1)[1] if "/" in n else n
        # snake_case 正規化 (空白 / 大文字 → `_`)
        base = base.strip().lower().replace(" ", "_")
        base = _NAME_INVALID.sub("", base)
        if base:
            parts.append(base)
    parts.append(weight.value)
    return _NAME_SAFE_SEP.join(parts)


def _build_config_yaml_block(persona_name: str, blend_prompt: str) -> str:
    """`config.yaml` の `agent.personalities.<name>` 配下に貼る YAML ブロックを返す。

    YAML ブロックリテラル記法 (`|`) を使い、Python 文字列 (hermes 側の docstring
    形式) として埋め込む。Pitfall を回避するため `hermes config set` 経由は使わず、
    必ず手動で `config.yaml` に貼り付ける運用とする。
    """
    # ヘッダーコメント
    timestamp = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = [
        f"# generated by hersona persistent at {timestamp}",
        "# このブロックを ~/.hermes/config.yaml の `agent.personalities:` 配下に貼り付けてください。",
        "# `hermes config set` を使うとネストした YAML が壊れるため、手動編集を強く推奨します。",
        "personalities:",
        f"  {persona_name}: |",
    ]
    # ブロックリテラル中身の各行を 4 スペースインデント
    for line in blend_prompt.splitlines() or [""]:
        lines.append(f"    {line}" if line else "    ")
    return "\n".join(lines)


def apply_personality(persona_name: str) -> str:
    """`hermes config set agent.personality <name>` を実行して即時切り替える。

    `agent.personality` はフラットなスカラー値なので `hermes config set` が安全に
    使える (Pitfall 8 の対象であるネスト YAML ではない)。

    Args:
        persona_name: 切り替える personality 名 (例: ``tsundere_keigo_strong``)

    Returns:
        "ok" (成功) または "hermes not found" / "error: <stderr>"

    Raises:
        なし (失敗は返り値で通知)
    """
    try:
        result = subprocess.run(
            ["hermes", "config", "set", "agent.personality", persona_name],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            return "ok"
        return f"error: {result.stderr.strip() or result.stdout.strip()}"
    except FileNotFoundError:
        return "hermes not found"
    except subprocess.TimeoutExpired:
        return "timeout"


def run_persistent(
    names: list[str],
    *,
    weight: str | WeightLevel = WeightLevel.MODERATE,
    profile: str = "default",
    without_soul: bool = False,
    without_config: bool = False,
    force: bool = False,
    config_yaml_output: str | Path | None = None,
    auto_config: bool = False,
    config_path: str | Path | None = None,
    apply: bool = False,
) -> PersistentResult:
    """persistent モードを実行する。

    Args:
        names: 適用する属性名 (例: `["personality/tsundere", "speech/keigo"]`)
        weight: 強度
        profile: SOUL.md 書き出し先 profile
        without_soul: True なら SOUL.md 書き出しをスキップ
        without_config: True なら config.yaml ブロック表示をスキップ
        force: 既存 SOUL.md と config.yaml エントリを強制上書き
        config_yaml_output: YAML ブロックをファイル書き出しするパス
        auto_config: True なら config.yaml に自動書き込みする (PyYAML 直接編集)
        config_path: auto_config 時の書き込み先 (省略時は ~/.hermes/config.yaml)
        apply: True なら `hermes config set agent.personality <name>` を実行する

    Returns:
        PersistentResult
    """
    if not names:
        raise ValueError("blend が空です (names は 1 つ以上必要)")

    level = coerce_level(weight)
    persona_name = _generate_persona_name(names, level)

    # blend_prompt を `attach.render_blend` で生成
    from hersona.core.attach import render_blend

    norm = [n.split("/", 1)[1] if "/" in n else n for n in names]
    blend = render_blend(norm, weight=level)
    blend_prompt = blend.prompt

    # 1) config.yaml ブロック (表示用) / 自動書き込み
    skipped: dict[str, str] = {}
    config_write_result: ConfigWriteResult | None = None

    if without_config:
        config_block = ""
        skipped["config"] = "user request (--without-config)"
    else:
        config_block = _build_config_yaml_block(persona_name, blend_prompt)
        # 任意のファイル書き出し (ブロック表示用)
        if config_yaml_output is not None:
            Path(config_yaml_output).write_text(config_block + "\n", encoding="utf-8")
        # 自動書き込み
        if auto_config:
            config_write_result = write_personality(
                persona_name,
                blend_prompt,
                config_path=Path(config_path) if config_path is not None else None,
                overwrite=force,
            )

    # 2) SOUL.md 自動書き出し
    soul_result: SoulRenderResult | None = None
    if without_soul:
        skipped["soul"] = "user request (--without-soul)"
    else:
        # 念のため属性の存在を validate ( render_blend が KeyError と同等 )
        for n in norm:
            load_attribute(n)  # raises KeyError if missing
        soul_result = write_soul(
            default_soul_path(profile),
            names,
            weight=level,
            append=False,
            overwrite=force,
            force=force,
        )

    # 3) hermes config set agent.personality <name>
    apply_result: str | None = None
    if apply:
        apply_result = apply_personality(persona_name)

    return PersistentResult(
        persona_name=persona_name,
        config_yaml_block=config_block,
        soul_result=soul_result,
        config_write_result=config_write_result,
        apply_result=apply_result,
        skipped=skipped,
    )
