"""SOUL.md 永続化 (ROADMAP §⑤ / docs/soul_md_persistence.md)。

hersona blend を Hermes One 公式の `SOUL.md` 形式に変換し、
`~/.hermes/profiles/<name>/SOUL.md` に書き出す。

公式 4 要素:
- Name
- Personality
- Tone
- Behavioral Guidelines

設計方針:
- core 共有: 合成は `attach.render_blend` に委譲し、本モジュールは整形と IO のみ。
- フレームワーク非依存: SOUL.md は plain Markdown テキストで出力。
- 安全: 既存ファイルは既定で上書き拒否 ( `overwrite=True` / `force=True` で許可)。
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from hersona import __version__
from hersona.core.attach import catchphrase_usage_directive, render_blend
from hersona.core.compatibility import CompatibilityMatrix
from hersona.core.intensity import content_language
from hersona.core.weight import WeightLevel, coerce_level, normalize_catchphrase

# Hermes One の SOUL.md 公式 4 要素にマップする既定の第一人称/二人称。
# Name フラグで上書き可能。
_DEFAULT_NAME = "Libra"
_DEFAULT_FIRST_PERSON = "私"
_DEFAULT_SECOND_PERSON = "あなた / きみ"

_MEMORY_KEY_RE = re.compile(r"^[a-z0-9_]{1,32}$")
_MAX_MEMORY_KEYS = 16
_MAX_MEMORY_VALUE_LEN = 512


@dataclass
class SoulRenderResult:
    """SOUL.md レンダリング結果。"""

    content: str  # ファイルに書き出す markdown 文字列
    output_path: Path  # 書き込み予定のパス
    blend_names: list[str]
    weight: WeightLevel
    lang: str
    name: str
    memory: dict[str, str] | None = None


def default_soul_path(profile: str = "default") -> Path:
    """Local Hermes CLI が実際に読む SOUL.md パスを返す。

    Local Hermes CLI の prompt_builder は `get_hermes_home() / "SOUL.md"`
    (`~/.hermes/SOUL.md`) を読む。profile 別パス
    (`~/.hermes/profiles/<profile>/SOUL.md`) は Hermes One 専用で
    Local CLI には反映されない。

    `profile` 引数は後方互換のため残す。

    Args:
        profile: 互換性のために残す引数 (現在は無視される)

    Returns:
        `~/.hermes/SOUL.md`
    """
    return Path.home() / ".hermes" / "SOUL.md"


def render_soul(
    names: list[str],
    *,
    weight: str | WeightLevel = WeightLevel.MODERATE,
    name: str = _DEFAULT_NAME,
    matrix: CompatibilityMatrix | None = None,
    public_root=None,
    user_root=None,
    title: str | None = None,
    intro: list[str] | None = None,
    agent_label: str | None = "Hermes Agent",
    memory: dict[str, str] | None = None,
) -> str:
    """blend を SOUL.md 形式の markdown 文字列にレンダリングする。

    Args:
        names: 適用する属性名 (例: `["personality/tsundere", "speech/keigo"]`)
        weight: 強度 (none / mild / moderate / strong)
        name: SOUL.md Name セクションの表示名
        matrix: 相性マトリクス (省略時自動ロード)
        public_root / user_root: 属性解決パス (テスト用)
        title: 先頭見出し (省略時は Hermes SOUL.md の既定見出し)
        intro: 見出し直下の引用 (blockquote) 行 (省略時は Hermes 既定)
        agent_label: Name セクションの「正式名称」ラベル (None なら行を省略)

    Returns:
        SOUL.md 形式の markdown 文字列

    Raises:
        ValueError: blend が空 / conflict 検出
        KeyError: 存在しない属性
    """
    if not names:
        raise ValueError("blend が空です (names は 1 つ以上必要)")

    # CLI と同じ正規化: `<category>/<name>` 形式なら name 部分だけ取り出す
    norm_names = [_normalize_name(n) for n in names]

    level = coerce_level(weight)
    blend = render_blend(
        norm_names,
        matrix=matrix,
        public_root=public_root,
        user_root=user_root,
        weight=level,
    )

    if blend.conflicts:
        # 公式 SOUL.md は人格の「正本」になるため、conflict は警告で済ませず拒否する。
        # (multi モードの挙動と整合)
        raise ValueError(
            f"blend に conflict 検出: {blend.conflicts}。SOUL.md 化は安全のため中止します。"
        )

    lang = content_language(blend.attributes)
    timestamp = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    blend_str = ", ".join(names)
    blend_meta = f"<!-- generated by hersona v{__version__} at {timestamp} -->\n"
    blend_meta += f"<!-- blend: {blend_str} -->\n"
    blend_meta += f"<!-- weight: {level.value} / lang: {lang} -->\n"
    blend_meta += "<!-- DO NOT EDIT: regenerate via `hersona soul ...` -->\n"

    body = _render_soul_body(
        blend=blend,
        weight=level,
        name=name,
        lang=lang,
        timestamp=timestamp,
        title=title,
        intro=intro,
        agent_label=agent_label,
    )
    memory = _validate_memory(memory)
    if memory:
        ctx = _render_recent_context(memory)
        footer_marker = "\n---\n\n_作成:"
        if footer_marker in body:
            prefix, suffix = body.rsplit(footer_marker, 1)
            body = f"{prefix}\n\n## Recent Context\n\n{ctx}\n{footer_marker}{suffix}"
        else:
            body = f"{body}\n\n## Recent Context\n\n{ctx}"
    return f"{blend_meta}\n{body}\n"


def write_soul(
    output: str | Path,
    names: list[str],
    *,
    weight: str | WeightLevel = WeightLevel.MODERATE,
    name: str = _DEFAULT_NAME,
    matrix: CompatibilityMatrix | None = None,
    public_root=None,
    user_root=None,
    append: bool = False,
    overwrite: bool = False,
    force: bool = False,
    memory: dict[str, str] | None = None,
) -> SoulRenderResult:
    """blend を SOUL.md 形式で `output` に書き出す。

    Args:
        output: 出力パス
        names: 適用する属性名
        weight: 強度
        name: SOUL.md Name セクションの表示名
        matrix: 相性マトリクス
        public_root / user_root: 属性解決パス
        append: True なら追記モード (既存ファイルに "## 追記" セクションを追加)
        overwrite: True なら上書きを許可
        force: True なら --force 相当 (確認なし)

    Returns:
        SoulRenderResult (content / output_path / blend_names / weight / lang / name)

    Raises:
        FileExistsError: 既存ファイルがあり overwrite=False の場合
        FileNotFoundError: 親ディレクトリが存在しない
        ValueError: blend が空 / conflict 検出
    """
    output_path = Path(output)
    if not output_path.parent.exists():
        raise FileNotFoundError(
            f"親ディレクトリが存在しません: {output_path.parent}。"
            "profile ディレクトリを先に作成してください (hermes profile create 等)。"
        )

    if output_path.exists() and not overwrite and not force and not append:
        raise FileExistsError(
            f"SOUL.md が既に存在します: {output_path}。"
            "上書きするには overwrite=True / force=True を使うか、append=True で追記してください。"
        )

    validated_memory = _validate_memory(memory)
    content = render_soul(
        names,
        weight=weight,
        name=name,
        matrix=matrix,
        public_root=public_root,
        user_root=user_root,
        memory=validated_memory,
    )

    if append and output_path.exists():
        # 追記モード: 既存ファイル末尾に "## 追記" セクションを追加
        timestamp = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
        blend_str = ", ".join(names)
        level = coerce_level(weight)
        appended = (
            f"\n\n---\n\n## 追記 ({timestamp})\n\n"
            f"_以下の blend を `hersona soul ... --append` で追記: {blend_str} (weight={level.value})_\n\n"
            f"{content}\n"
        )
        with open(output_path, "a", encoding="utf-8") as f:
            f.write(appended)
    else:
        # 上書きモード
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

    return SoulRenderResult(
        content=content,
        output_path=output_path,
        blend_names=list(names),
        weight=coerce_level(weight),
        lang=_detect_lang_from_names(
            names, matrix=matrix, public_root=public_root, user_root=user_root
        ),
        name=name,
        memory=validated_memory,
    )


def resolve_memory(
    *,
    memory: dict[str, str] | None = None,
    memory_file: str | Path | None = None,
) -> dict[str, str] | None:
    """Resolve caller-supplied memory from inline dict or JSON file."""
    if memory is not None and memory_file is not None:
        raise ValueError("--memory and --memory-file are mutually exclusive")
    if memory_file is not None:
        with open(memory_file, encoding="utf-8") as f:
            memory = json.load(f)
    return _validate_memory(memory)


def _detect_lang_from_names(
    names: list[str],
    *,
    matrix=None,
    public_root=None,
    user_root=None,
) -> str:
    """blend の先頭属性からコンテンツ言語を検出する (ヘルパー)。"""
    if not names:
        return "ja"
    norm = [_normalize_name(n) for n in names]
    blend = render_blend(
        norm, matrix=matrix, public_root=public_root, user_root=user_root
    )
    return content_language(blend.attributes)


# --- 内部 ---------------------------------------------------------------


def _normalize_name(name: str) -> str:
    """`<category>/<name>` 形式なら name 部分を返す (CLI と整合)。"""
    return name.split("/", 1)[1] if "/" in name else name


def _validate_memory(memory: dict | None) -> dict | None:
    """Validate caller-supplied memory dict (shape only; content is caller-owned)."""
    if memory is None:
        return None
    if not isinstance(memory, dict):
        raise ValueError(f"memory must be dict[str, str], got {type(memory).__name__}")
    if not memory:
        return None
    if len(memory) > _MAX_MEMORY_KEYS:
        raise ValueError(f"memory has {len(memory)} keys (> {_MAX_MEMORY_KEYS})")
    for key, value in memory.items():
        if not isinstance(key, str) or not _MEMORY_KEY_RE.match(key):
            raise ValueError(
                f"memory key invalid: {key!r} (must match {_MEMORY_KEY_RE.pattern})"
            )
        if not isinstance(value, str) or not value:
            raise ValueError(f"memory[{key!r}] must be non-empty str")
        if len(value) > _MAX_MEMORY_VALUE_LEN:
            raise ValueError(
                f"memory[{key!r}] length {len(value)} > {_MAX_MEMORY_VALUE_LEN}"
            )
    return memory


def _escape_memory_text(text: str) -> str:
    """Safelist markdown escape for user-supplied memory values."""
    replacements = (
        ("`", "\\`"),
        ("##", "\\#\\#"),
        ("[", "\\["),
        ("]", "\\]"),
        ("*", "\\*"),
        ("_", "\\_"),
    )
    escaped = text
    for old, new in replacements:
        escaped = escaped.replace(old, new)
    return escaped


def _render_recent_context(memory: dict[str, str]) -> str:
    """Assemble the Recent Context markdown block."""
    lines: list[str] = []
    for key, value in memory.items():
        safe_value = _escape_memory_text(value)
        lines.append(f"### {key}: {safe_value}")
    return "\n".join(lines)


_DEFAULT_TITLE = "# SOUL — Hermes Agent ペルソナ定義"
_DEFAULT_INTRO = [
    "> 公式仕様: hermesagents.cc の \"Soul\" スクリーン参照。",
    "> 含まれるべき 4 要素: name / personality / tone / behavioral guidelines。",
    "> 効果: 次回セッション開始時から即時反映。再起動不要。",
]


def _render_soul_body(
    *,
    blend,
    weight: WeightLevel,
    name: str,
    lang: str,
    timestamp: str,
    title: str | None = None,
    intro: list[str] | None = None,
    agent_label: str | None = "Hermes Agent",
) -> str:
    """SOUL.md の本文 (公式 4 要素) を組み立てる。"""
    lines: list[str] = [title if title is not None else _DEFAULT_TITLE]
    lines.append("")
    for intro_line in (intro if intro is not None else _DEFAULT_INTRO):
        lines.append(intro_line)
    lines.append("")

    # --- 1. Name ---
    lines.append("## 1. Name (エージェント名)")
    lines.append("")
    lines.append(f"- **表示名**: {name}")
    if agent_label:
        lines.append(f"- **正式名称**: {agent_label} ({name} ペルソナ)")
    lines.append(f"- **一人称**: {_DEFAULT_FIRST_PERSON}")
    lines.append(f"- **二人称**: {_DEFAULT_SECOND_PERSON}")
    lines.append("")

    # --- 2. Personality ---
    lines.append("## 2. Personality (性格特性)")
    lines.append("")
    personality_attrs = [
        a for a in blend.attributes if a.get("attribute_category") == "personality"
    ]
    if not personality_attrs:
        lines.append("(personality 属性が指定されていません)")
        lines.append("")
    else:
        for attr in personality_attrs:
            attr_id = (
                f"{attr.get('attribute_category', '?')}/{attr.get('attribute_name', '?')}"
            )
            lines.append(f"### 2.{personality_attrs.index(attr) + 1} {attr_id}")
            lines.append("")
            desc = attr.get("description", "").strip()
            if desc:
                lines.append(f"> {desc}")
                lines.append("")
            # 言語拘束: content_i18n.<lang> があれば優先
            traits = _resolve_lang_field(attr, "core_traits", lang)
            if traits:
                lines.append("**core_traits**:")
                for t in traits:
                    lines.append(f"- {t}")
                lines.append("")

        # 互換 / 衝突 (archetype / visual / hobby もここに集約)
        other_attrs = [
            a for a in blend.attributes if a.get("attribute_category") != "personality"
        ]
        if other_attrs:
            lines.append("### 2.x 互換 / 衝突 (他カテゴリ属性)")
            lines.append("")
            for attr in other_attrs:
                attr_id = (
                    f"{attr.get('attribute_category', '?')}/{attr.get('attribute_name', '?')}"
                )
                compat = attr.get("compatible_archetypes", []) or []
                conflicts = attr.get("conflicts_with", []) or []
                lines.append(f"- **{attr_id}**")
                if compat:
                    lines.append(f"  - compatible: {', '.join(compat)}")
                if conflicts:
                    lines.append(f"  - conflicts: {', '.join(conflicts)}")
            lines.append("")

    # --- 3. Tone ---
    lines.append("## 3. Tone (口調)")
    lines.append("")
    speech_attrs = [
        a for a in blend.attributes if a.get("attribute_category") == "speech"
    ]
    if not speech_attrs:
        lines.append("(speech 属性が指定されていません)")
        lines.append("")
    else:
        for idx, attr in enumerate(speech_attrs, start=1):
            attr_id = (
                f"{attr.get('attribute_category', '?')}/{attr.get('attribute_name', '?')}"
            )
            lines.append(f"### 3.{idx} {attr_id}")
            lines.append("")
            tone = _resolve_lang_str(attr, "tone", lang)
            if tone:
                lines.append(f"**tone**: {tone}")
                lines.append("")
            catchphrases = _resolve_lang_field(attr, "catchphrases", lang)
            if catchphrases:
                lines.append("**catchphrases**:")
                for c in catchphrases:
                    nc = normalize_catchphrase(c)
                    if nc["when"]:
                        lines.append(f"- {nc['phrase']} — {nc['when']}")
                    else:
                        lines.append(f"- {nc['phrase']}")
                lines.append("")
                lines.append(catchphrase_usage_directive(lang))
                lines.append("")
            endings = _resolve_lang_field(attr, "sentence_endings", lang)
            if endings:
                lines.append(f"**sentence_endings**: {' / '.join(endings)}")
                lines.append("")
    lines.append("")

    # --- 4. Behavioral Guidelines ---
    lines.append("## 4. Behavioral Guidelines (行動指針)")
    lines.append("")
    lines.append(f"### 4.1 鉄則 (強度: {weight.value})")
    lines.append("")
    lines.append(_weight_guidelines_for(weight))
    lines.append("")
    lines.append("### 4.2 blend 共通の行動ルール")
    lines.append("")
    rules: list[str] = []
    for attr in blend.attributes:
        rules.extend(_extract_behavior_rules(attr))
    if rules:
        # 重複排除 (順序保持)
        seen: set[str] = set()
        for r in rules:
            if r not in seen:
                seen.add(r)
                lines.append(f"- {r}")
    else:
        lines.append("- (blend に明示的な行動ルールなし)")
    lines.append("")

    # --- フッター ---
    lines.append("---")
    lines.append("")
    lines.append(
        f"_作成: {timestamp} / hersona v{__version__} + Hermes One 公式仕様準拠_"
    )

    return "\n".join(lines)


def _resolve_lang_field(attr: dict, key: str, lang: str) -> list[str]:
    """content_i18n.<lang>.<key> があれば優先、なければ BASE の key を返す。"""
    i18n = attr.get("content_i18n", {}) or {}
    localized = i18n.get(lang, {}) or {}
    value = localized.get(key)
    if value:
        return list(value)
    return list(attr.get(key, []) or [])


def _resolve_lang_str(attr: dict, key: str, lang: str) -> str:
    """content_i18n.<lang>.<key> があれば優先、なければ BASE の key を返す (str 版)。"""
    i18n = attr.get("content_i18n", {}) or {}
    localized = i18n.get(lang, {}) or {}
    value = localized.get(key)
    if isinstance(value, str) and value:
        return value
    base = attr.get(key, "")
    return base if isinstance(base, str) else ""


def _weight_guidelines_for(weight: WeightLevel) -> str:
    """強度別の行動ガイドライン (SOUL.md 用)。"""
    guidance = {
        WeightLevel.NONE: "- 特性として質的にのみ効かせる。口癖・語尾の顕在化は最小限。",
        WeightLevel.MILD: "- ほのかに滲ませる。catchphrases は時折、語尾は控えめに。",
        WeightLevel.MODERATE: "- 標準的な強度。catchphrases と語尾を自然な頻度で用いる。",
        WeightLevel.STRONG: "- 明確に顕在化させる。catchphrases を多用し、語尾・一人称を徹底。",
    }
    return guidance[weight]


def _extract_behavior_rules(attr: dict) -> list[str]:
    """属性の behavioral_guidelines / rules / notes から行動ルール文字列を抽出。"""
    rules: list[str] = []
    for key in ("behavioral_guidelines", "rules", "notes"):
        value = attr.get(key)
        if isinstance(value, str) and value:
            for line in value.splitlines():
                line = line.strip()
                if line and not line.startswith("#"):
                    rules.append(line)
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, str) and item.strip():
                    rules.append(item.strip())
    return rules
